// src/components/LebenslaufPlaceholder.vue
<template>
  <div class="text-center text-gray-500 p-10 border border-dashed border-orange-300 rounded-xl bg-orange-50">
    <h2 class="text-xl font-semibold text-orange-600 mb-2">🚧 Lebenslauf-Generator</h2>
    <p>Hier wird künftig ein eigener Lebenslauf-Generator mit vielen Funktionen zur Verfügung stehen.</p>
  </div>
</template>

<script setup>
// Keine Logik notwendig
</script>

// src/components/LebenslaufPlaceholder.tsx
import React from 'react';

export default function LebenslaufPlaceholder() {
  return (
    <div className="text-center text-gray-500 p-10 border border-dashed border-orange-300 rounded-xl bg-orange-50">
      <h2 className="text-xl font-semibold text-orange-600 mb-2">🚧 Lebenslauf-Generator</h2>
      <p>Hier wird künftig ein eigener Lebenslauf-Generator mit vielen Funktionen zur Verfügung stehen.</p>
    </div>
  );
}
